local player = game.Players.LocalPlayer
local mouse = player:GetMouse()
bind = "r" -- has to be lowercase
mouse.KeyDown:connect(function(key)
if key == bind then do 
local args = {
    [1] = "Turkey"
}

workspace.Events.Morph.Player:FireServer(unpack(args))


end
end
end)
local player = game.Players.LocalPlayer
local mouse = player:GetMouse()
bind = "e" -- has to be lowercase
mouse.KeyDown:connect(function(key)
if key == bind then do 
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

for _, v in next, game.Players.LocalPlayer.Character.Torso:GetDescendants() do
       if v and v:IsA"Weld" then
           v:destroy()
       end
end
local player = game.Players.LocalPlayer
local mouse = player:GetMouse()
bind = "t" -- has to be lowercase
mouse.KeyDown:connect(function(key)
if key == bind then do 
for i,v in pairs(game.Players.LocalPlayer.Character.Torso:GetDescendants()) do
if v.Name == "Part" then
v.Parent = workspace
end
end
end
end
end)
local player = game.Players.LocalPlayer
local mouse = player:GetMouse()
bind = "e" -- has to be lowercase
mouse.KeyDown:connect(function(key)
if key == bind then do 
for i,v in pairs(game.Players.LocalPlayer.Character.Torso:GetDescendants()) do
if v.Name == "Mesh" then
v:Destroy()
end
end
end
end
end)
while wait() do
for i,v in pairs(game.Players.LocalPlayer.Character:GetDescendants()) do
    if  v.Name == "IsaMorph" then do
        v:destroy() end else end
    end
end
end
end
end)